#use_frameworks!

platform :ios, '9.0'

target 'GJTDebugerManager_Example' do
  pod 'GJTDebugerManager', :path => '../'

  target 'GJTDebugerManager_Tests' do
    inherit! :search_paths

    
  end
end
