#use_frameworks!

platform :ios, '9.0'

target 'GJTDebugManager_Example' do
  pod 'GJTDebugManager', :path => '../'

  pod 'GJTAdditionKit',:path => '../../GJTAdditionKit'
  
  target 'GJTDebugManager_Tests' do
    inherit! :search_paths

    
  end
end
